# Generated by Django 3.1.4 on 2021-01-18 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completion',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.CharField(default='low', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
