# Generated by Django 3.1.4 on 2021-01-18 01:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default='False')),
                ('task', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added_year', models.CharField(default='0000', max_length=4)),
                ('date_added_month', models.CharField(default='00', max_length=2)),
                ('date_added_day', models.CharField(default='00', max_length=2)),
                ('date_added_week', models.CharField(default='00', max_length=2)),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('desc', models.TextField(default='enter', max_length=500)),
                ('hours_planned', models.IntegerField(default=0)),
                ('hours_worked', models.IntegerField(default=0)),
                ('priority', models.CharField(max_length=32)),
                ('user_written', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
